[workspace]
members = ["crates/*", "examples/*"]
resolver = "2"

[workspace.dependencies]
yellowstone-grpc-client = { version = "1.16.0+solana.2.0.2", git = "https://github.com/rpcpool/yellowstone-grpc", branch = "master" }
yellowstone-grpc-proto = { version = "1.15.0+solana.2.0.2", git = "https://github.com/rpcpool/yellowstone-grpc", branch = "master", default-features = false }
yellowstone-vixen-parser = { path = "crates/parser", version = "0.0.0" }
yellowstone-vixen = { path = "crates/runtime", version = "0.0.0" }
yellowstone-vixen-core = { path = "crates/core", version = "0.0.0" }
yellowstone-vixen-mock = { path = "crates/mock", version = "0.0.0" }
