[package]
name = "yellowstone-vixen-parser"
description = "Vixen program parsers for the solana program library."
version = "0.0.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/rpcpool/yellowstone-vixen"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

#TODO: replace commented code after completeion

[dependencies]
spl-associated-token-account = "4.0.0"
spl-pod = "0.3.0"
# spl-token = {version="6.0.0",optional = true}
# spl-token = {version="6.0.0",optional = true}
spl-token = { version = "6.0.0" }
# spl-token-2022 = { version = "4.0.1", optional = true }
# spl-type-length-value = { version = "0.5.0", optional = true }
spl-type-length-value = "0.5.0"
spl-token-2022 = { version = "4.0.0" }
spl-token-group-interface = "0.3.0"
spl-token-metadata-interface = "0.4.0"

yellowstone-vixen-core = { path = "../core" }

# [features]
# default = []
# token-extensions = ["spl-token-2022","spl-type-length-value", "spl-pod"]
# token-program = ["spl-token"]
# associated-token-program = ["spl-token-2022"]
