[package]
name = "yellowstone-vixen-mock"
description = "Mock implementation of the Vixen Parsers for testing."
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yellowstone-grpc-proto = { workspace = true }
yellowstone-vixen-parser = { path = "../parser" }
solana-client = "2.0.3"
solana-sdk = "2.0.3"
yellowstone-vixen-core = { path = "../core" }
tokio = "1.39.2"
serde = "1.0.204"
serde_json = "1.0.121"
surf = "2.3.2"
base64 = "0.22.1"
