[package]
name = "yellowstone-vixen-core"
description = "Core types for Vixen"
# authors = ["TODO"]
version = "0.0.0"
edition = "2021"
license = "AGPL-3.0-or-later"
repository = "https://github.com/rpcpool/yellowstone-vixen"

[dependencies]
bs58 = "0.5.1"
thiserror = "1.0.59"
yellowstone-grpc-proto = { workspace = true }
